name: Test All Models

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:

  Job:

    strategy:
      matrix:
        Type: [classic, vincular]
        Sub-Type: [containment, avoidance]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python
        run: python3 -m venv code/.venv
      - name: Create Directories
        run: |
          mkdir -p tests/params/classical/containment
          mkdir -p tests/params/classical/avoidance
          mkdir -p tests/output/classical/containment
          mkdir -p tests/output/classical/avoidance
          mkdir -p tests/params/vincular/containment
          mkdir -p tests/params/vincular/avoidance
          mkdir -p tests/output/vincular/containment
          mkdir -p tests/output/vincular/avoidance
          mkdir -p tests/params/bivincular/containment
          mkdir -p tests/params/bivincular/avoidance
          mkdir -p tests/output/bivincular/containment
          mkdir -p tests/output/bivincular/avoidance
      - name: Set Conjure Path
        run: |
          echo "conjure-v2.5.1-linux-with-solvers" >> $GITHUB_PATH
      - name: Generate Params
        run: |
          ./tests/generate_params.sh ${{ matrix.Type }} ${{ matrix.Sub-Type }}
      - name: Solve Params
        run: |
          ./tests/solve_params.sh ${{ matrix.Type }} ${{ matrix.Sub-Type }}
      - name: Run Tests
        run: |
          ./tests/run_tests.sh ${{ matrix.Type }} ${{ matrix.Sub-Type }}