name: Test All Models

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python
        run: python3 -m venv code/.venv
      - name: Create Directories
        run: |
          mkdir tests/params
          mkdir tests/params/classical
          mkdir tests/params/classical/containment
          mkdir tests/params/classical/avoidance
          mkdir tests/output
          mkdir tests/output/classical
          mkdir tests/output/classical/containment
          mkdir tests/output/classical/avoidance
      - name: Set Conjure Path
        run: |
          echo "conjure-v2.5.1-macos-arm-with-solvers" >> $GITHUB_PATH
      - name: Generate Params
        run: |
          ./tests/generate_params.sh
      - name: Solve Params
        run: |
          ./tests/solve_classical_containment_params.sh
          ./tests/solve_classical_avoidance_params.sh
      - name: Run Classical Tests
        run: |
          ./tests/classical.sh
