name: Test All Models

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  Generate-Params:
    runs-on: ubuntu-latest
    outputs:
      tests-path: ${{ steps.set-tests-path.outputs.tests-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python
        run: python3 -m venv code/.venv
      - name: Create Directories
        id: set-tests-path
        run: |
          mkdir -p tests/params/classical/containment
          mkdir -p tests/params/classical/avoidance
          mkdir -p tests/output/classical/containment
          mkdir -p tests/output/classical/avoidance
          echo "::set-output name=tests-path::$(pwd)/tests"
      - name: Generate Params
        run: |
          ./tests/generate_params.sh

  Solve-Classical-Containment:
    runs-on: ubuntu-latest
    needs: Generate-Params
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy generated files
        run: cp -r ${{ needs.Generate-Params.outputs.tests-path }}/ .
      - name: Set Conjure Path
        run: |
          echo "conjure-v2.5.1-linux-with-solvers" >> $GITHUB_PATH
      - name: Solve Params
        run: |
          ./tests/solve_classical_containment_params.sh

  Solve-Classical-Avoidance:
    runs-on: ubuntu-latest
    needs: Generate-Params
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy generated files
        run: cp -r ${{ needs.Generate-Params.outputs.tests-path }}/ .
      - name: Set Conjure Path
        run: |
          echo "conjure-v2.5.1-linux-with-solvers" >> $GITHUB_PATH
      - name: Solve Params
        run: |
          ./tests/solve_classical_avoidance_params.sh

  Run-Classical-Containment-Tests:
    runs-on: ubuntu-latest
    needs: Solve-Classical-Containment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy generated files
        run: cp -r ${{ needs.Solve-Classical-Containment.outputs.tests-path }}/ .
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python
        run: python3 -m venv code/.venv
      - name: Run Classical Tests
        run: |
          python3 tests/classical_test.py containment

  Run-Classical-Avoidance-Tests:
    runs-on: ubuntu-latest
    needs: Solve-Classical-Avoidance
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy generated files
        run: cp -r ${{ needs.Solve-Classical-Avoidance.outputs.tests-path }}/ .
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python
        run: python3 -m venv code/.venv
      - name: Run Classical Tests
        run: |
          python3 tests/classical_test.py avoidance
